apiVersion: v2
kind: Namespace
metadata:
  name: nginx
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v2
kind: Namespace
metadata:
  name: wordpress
  annotations:
    argocd.argoproj.io/sync-wave: "-1"