apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-3ridge
  annotations:
    argocd.argoproj.io/sync-wave: "-1"